name: confluent-kafka-javascript
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/confluent-kafka-javascript
codeowners:
  enable: true
semaphore:
  enable: true
  tasks:
  - name: post-install
    scheduled: false
    branch: "master"
    pipeline_file: .semaphore/post_install.yml
    parameters:
    - name: LIBRARY_VERSION
      required: true
      description: "Which library version to install."
      default_value: "latest"
sonarqube:
  enable: true
  coverage_reports:
    - "./coverage/lcov.info"
  coverage_exclusions:
    - "**/*.pb.*"
    - "**/mk-include/**/*"
    - "examples/**"
  languages:
    - javascript
